- hosts: cluster
  remote_user: master
  become: yes
  become_user: root
  roles:
  - { role: filebeat }

- hosts: server2
  remote_user: master
  become: yes
  become_user: root
  roles:
  - { role: logstash }
